version: '3.7'
services:
  db:
    build: 
      context: .
      dockerfile: ./Database/Dockerfile
    ports:
      - 1433:1433
    volumes:
      - ./Database/mssqldata:/var/opt/mssql/data
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=P@ssw0rd123
      - TZ=Europe/Kiev
      - MSSQL_USER=sa